name: Publish

on:
  release:
    types:
      - published
      # - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: author/action-publish@stable
        with:
          # Optionally specify the directories to scan
          # for modules. If this is not specified, the
          # root directory is scanned.
          scan: "./packages/button"
          # Optionally force publishing as a public
          # module. We don't recommend setting this,
          # unless you have a very specific use case.
          force: true
        env:
          # Typically an npm token
          REGISTRY_TOKEN: "${{ secrets.NPM_AUTH_TOKEN }}"
