name: CI

on:
  push:
  workflow_dispatch:

jobs:
  packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.9.1
      - run: $(echo pnpm -s list-packages)
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"package\":$(pnpm -s list-packages)}"
  build:
    needs: packages
    strategy:
      matrix: ${{ fromJson(needs.packages.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ matrix.package }}

      - id: package-path
        run: echo "::set-output name=path::$(echo ${{ matrix.package }} | sed -e 's/@sceneui\///g')"
        shell: bash

      - id: check
        uses: EndBug/version-check@v1
        with:
          file-name: base/packages/${{ steps.package-path.outputs.path }}/package.json

      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'
