name: CI

on:
  push:
  workflow_dispatch:

jobs:
  packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.9.1
      - run: $(echo pnpm -s list-packages)
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"package\":$(pnpm -s list-packages)}"

  build:
    needs: packages
    strategy:
      matrix: ${{ fromJson(needs.packages.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo ${{ matrix.package }}

      - id: package-path
        run: echo "::set-output name=path::$(echo ${{ matrix.package }} | sed -e 's/@sceneui\///g')"
        shell: bash

      - name: Check package version
        id: check
        uses: PostHog/check-package-version@v2
        with:
          path: ./packages/${{ steps.package-path.outputs.path }}/

      - name: Echo output
        uses: pnpm/action-setup@v2
        with:
          version: 6.9.1

        # if: steps.check.outputs.is-new-version == 'true'

        run: |
          echo "Latest published version: ${{ steps.check.outputs.published-version }}"
          echo "Repo version: ${{ steps.check.outputs.committed-version }}"
          pnpm publish ./packages/${{ steps.package-path.outputs.path }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
