name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org/"
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - uses: pnpm/action-setup@v2
        with:
          version: 6.9.1
      - run: pnpm publish ./packages/button --access=public --no-git-checks
